In [12]:
x_vals = np.random.rand(50)
x_train = np.asarray(x_vals,dtype=np.float32).reshape(-1,1)
m = 1
alpha = np.random.rand(1)
beta = np.random.rand(1)
y_correct = np.asarray([2*i+m for i in x_vals], dtype=np.float32).reshape(-1,1)

In [16]:
np.asarray([2*i+m for i in x_vals], dtype=np.float32).reshape(-1,1)

array([[1.8091896],
       [1.0663857],
       [1.316486 ],
       [2.0529387],
       [1.9463491],
       [2.5184197],
       [2.9301991],
       [2.1991158],
       [1.3309779],
       [1.1336826],
       [2.2464201],
       [1.2806014],
       [2.3357491],
       [1.9373571],
       [1.7221426],
       [1.551168 ],
       [1.4047018],
       [2.5141704],
       [2.509337 ],
       [2.2965522],
       [1.579371 ],
       [2.016176 ],
       [1.6278304],
       [2.1860366],
       [2.0204744],
       [2.2485266],
       [1.1297   ],
       [1.3121358],
       [1.517021 ],
       [1.3295214],
       [2.4398112],
       [2.25864  ],
       [1.819376 ],
       [1.6694683],
       [1.2092364],
       [1.3506554],
       [1.8955148],
       [2.2019558],
       [2.2586846],
       [2.787262 ],
       [1.6533962],
       [2.953482 ],
       [2.7354634],
       [1.9587709],
       [1.1041781],
       [1.901738 ],
       [2.7730415],
       [2.3700387],
       [2.068452 ],
       [2.0755303]],

In [8]:
np.asarray(x_vals,dtype=np.float32).reshape(-1,1)

array([[0.46982285],
       [0.09084725],
       [0.48526224],
       [0.9553331 ],
       [0.8522279 ],
       [0.4613693 ],
       [0.8901014 ],
       [0.8032201 ],
       [0.09630492],
       [0.10400802],
       [0.97381914],
       [0.9904049 ],
       [0.86626375],
       [0.9162528 ],
       [0.5137088 ],
       [0.6198432 ],
       [0.6740112 ],
       [0.68815744],
       [0.6774027 ],
       [0.18930796],
       [0.92817515],
       [0.18065976],
       [0.46651453],
       [0.754764  ],
       [0.6653766 ],
       [0.2722507 ],
       [0.879089  ],
       [0.58458686],
       [0.85991603],
       [0.9888284 ],
       [0.32732993],
       [0.4645348 ],
       [0.7848241 ],
       [0.5955093 ],
       [0.6276056 ],
       [0.43596855],
       [0.28830963],
       [0.6303123 ],
       [0.18306392],
       [0.8070808 ],
       [0.4173316 ],
       [0.03657546],
       [0.5778475 ],
       [0.17746747],
       [0.5967958 ],
       [0.69090307],
       [0.71087366],
       [0.094

In [10]:
np.random.rand(1)

array([0.11138966])

In [9]:
np.random.rand(1)

array([0.10402207])